import {StyleSheet} from 'react-native';
import {COLORS} from '../theme/colors';

const CommonStyles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.backdrop,
    opacity: 0.5,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  margin: {margin: 20},
  marginTop: {marginTop: 24},
  marginBottom10: {marginBottom: 10},
  marginBottom20: {marginBottom: 20},
  padding: {padding: 20},
  padding16: {padding: 16},
  padding12: {padding: 12},
  padding10: {padding: 10},
  padding5: {padding: 5},
  paddingL10: {paddingLeft: 10},
  paddingR10: {paddingRight: 10},
  flexOne: {flex: 1},
  flexGrow: {flexGrow: 1},
  flexRow: {flexDirection: 'row'},
  flexColumn: {flexDirection: 'column'},
  rowSpaceBetween: {flexDirection: 'row', justifyContent: 'space-between'},
  rowSpaceBetweenFlex: {flex: 1, justifyContent: 'space-between'},
  flexRowGap: {flexDirection: 'row', gap: 20},
  rowCenter: {flexDirection: 'row', justifyContent: 'center'},
  flexOneMargin: {flex: 1, margin: 20},
  marginHorizontal20: {marginHorizontal: 20},
  marginHorizontal24: {marginHorizontal: 24},
  marginVertical20: {marginVertical: 20},
  marginHorizontal16: {marginHorizontal: 16},
  marginHorizontal10: {marginHorizontal: 10},
  marginVertical16: {marginVertical: 16},
  marginVertical10: {marginVertical: 10},
  marginL10: {marginLeft: 10},
  marginR10: {marginRight: 10},
  scrollViewContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  marginVerticalHorizontal: {
    marginHorizontal: 20,
    marginVertical: 20,
  },
  verticalDivider: {width: 1, height: '100%', color: COLORS.lightGrey2},
  horizontalDivider: {
    width: '100%',
    height: 1,
    color: COLORS.lightGrey2,
    marginVertical: 16,
  },
  horizontalDivider2: {backgroundColor: COLORS.grey, marginBottom: 10},
  accordionHeadingStyle: {
    backgroundColor: COLORS.white,
    shadowRadius: 0,
    elevation: 0,
  },
  accordionTitleStyle: {
    color: COLORS.darkOrange,
    fontFamily: 'soleto_medium',
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 20,
    paddingLeft: 0,
  },
  gap10: {gap: 10},
  pressableFeedback: {opacity: 0.6},
  textAlignCenter: {textAlign: 'center'},
  comment: {height: 100},
  paddingH10: {paddingHorizontal: 10},
  dateViewStyle: {marginHorizontal: 5, marginTop: 10},
  justifyContentSpaceAround: {justifyContent: 'space-around'},
  flatListMargin: {margin: 20, marginBottom: 0},
  flexOneMargin0: {flex: 1, margin: 0},
  selfFlexEnd: {alignSelf: 'flex-end'},
  rowAlignCenter: {flexDirection: 'row', alignItems: 'center'},
});

export default CommonStyles;
